const test = require('node:test');
const assert = require('node:assert/strict');
const { planInsertion, insertGenerated, contextFor, removeGenerated, findLegacyMarkerRange, findKnownSyntheticRemnantRanges } = require('../src/content/editor-planner.js');
const { generateSnippet, generateProgram, contextKind, generateContextSnippet } = require('../src/content/snippet-generator.js');
const { TextBufferAdapter, normalizeLanguage } = require('../src/content/editor-bridge.js');
const { hashText } = require('../src/shared/core.js');

function roundTrip(source, language) {
  const plan=planInsertion(source,language), snippet=generateSnippet(language,source,1), result=insertGenerated(source,plan,snippet), context=contextFor(source,plan.index);
  assert.ok(result.start>source.indexOf('{') || language==='python');
  const journal={generatedContent:result.generated,insertionPosition:result.start,contextBefore:context.before,contextAfter:context.after,maximumUnsavedTailAllowance:512};
  const cleaned=removeGenerated(result.source,journal); assert.equal(cleaned.ok,true); assert.equal(cleaned.source,source); return {plan,result,journal};
}
test('C++ insertion is inside function and cleanup is exact',()=>roundTrip(`class Solution {\npublic:\n    int solve(vector<int>& A) {\n        int old = 2;\n        return old;\n    }\n};`,'cpp'));
test('Java insertion is inside method and cleanup is exact',()=>roundTrip(`class Solution {\n    public int solve(int[] A) {\n        int old = 2;\n        return old;\n    }\n}`,'java'));
test('Python insertion preserves initial docstring',()=>{const source=`class Solution:\n    def solve(self, A):\n        \"\"\"keep this docstring\"\"\"\n        return len(A)\n`;const {result}=roundTrip(source,'python');assert.ok(result.source.indexOf('keep this docstring')<result.start)});
test('JavaScript and TypeScript insertion and cleanup',()=>{roundTrip(`class Solution { solve(A) { const old = 1; return old; } }`,'javascript');roundTrip(`class Solution { solve(A: number[]): number { const old = 1; return old; } }`,'typescript')});
test('existing identifiers use semantic collision alternatives instead of numeric suffixes',()=>{const text=generateSnippet('cpp','int values; int total; int count;');assert.match(text,/numbers/);assert.match(text,/sum/);assert.doesNotMatch(text,/values2|total2|labValue|automationValue|generatedCount|syntheticVariable/)});
test('generated traversal patterns rotate between questions',()=>{for(const language of ['cpp','java','python','javascript','typescript'])assert.equal(new Set(Array.from({length:12},(_,i)=>generateSnippet(language,'',i))).size,12)});
test('program generation combines multiple collision-safe traversal phases',()=>{for(const language of ['cpp','java','python','javascript','typescript']){const program=generateProgram(language,'',16);assert.ok(program.split('\n').length>=14);assert.notEqual(program,generateProgram(language,'',17))}});
test('problem context selects coherent C++ vocabulary without cumulative numeric suffixes',()=>{const snippet=generateContextSnippet('cpp','class Solution {};',17,'Sort a linked list of 0s, 1s and 2s');assert.equal(contextKind('linked list node traversal'),'linked-list');assert.match(snippet,/node|Node|Values|value/);assert.doesNotMatch(snippet,/answer\d+|data\d+|value\d+/)});
test('outside edits survive exact cleanup',()=>{const source=`class Solution { int solve() { return 1; } };`,{result,journal}=roundTrip(source,'cpp');const changed='HEADER\n'+result.source+'\nTAIL';journal.insertionPosition+=7;const cleaned=removeGenerated(changed,journal);assert.equal(cleaned.source,'HEADER\n'+source+'\nTAIL')});
test('generated-range modification is refused and forced cleanup uses anchors',()=>{const source=`class Solution { int solve() { return 1; } };`,{result,journal}=roundTrip(source,'cpp');const changed=result.source.slice(0,result.start+5)+'X'+result.source.slice(result.start+6);assert.equal(removeGenerated(changed,journal).ok,false);const forced=removeGenerated(changed,journal,true);assert.equal(forced.ok,true);assert.equal(forced.source,source)});
test('recovery journal exact range cleanup',()=>{const source=`class Solution { int solve() { return 1; } };`,{result,journal}=roundTrip(source,'cpp');journal.runId='r';journal.problemId='p';journal.problemUrl='u';journal.language='cpp';journal.lastUpdateTimestamp=1;assert.equal(removeGenerated(result.source,journal).source,source);assert.equal(hashText(journal.generatedContent),hashText(result.generated))});
test('caret follows inserted text and returns to original position',async()=>{const adapter=new TextBufferAdapter('abcdef');await adapter.begin('s',3);await adapter.insert('XYZ');assert.equal(adapter.caret,6);await adapter.remove();assert.equal(adapter.value,'abcdef');assert.equal(adapter.caret,3)});
test('text buffer refuses modified generated range',async()=>{const adapter=new TextBufferAdapter('abcdef');await adapter.begin('s',3);await adapter.insert('XYZ');adapter.value=adapter.value.replace('XYZ','XQZ');await assert.rejects(adapter.remove(),/External modification/)});
test('legacy visible markers can be identified for one-time cleanup',()=>{const source='before\n/* GFG_TRAVERSAL_LAB_START */\nint x;\n/* GFG_TRAVERSAL_LAB_END */\nafter';const r=findLegacyMarkerRange(source);assert.equal(source.slice(0,r.start)+source.slice(r.end),'before\n\nafter')});
test('live GFG language labels normalize correctly',()=>{assert.equal(normalizeLanguage('C++ (17)'),'cpp');assert.equal(normalizeLanguage('Java (21)'),'java');assert.equal(normalizeLanguage('Python3'),'python');assert.equal(normalizeLanguage('Javascript (Node v22)'),'javascript')});
test('known duplicate generated blocks are found without selecting the solution function',()=>{const source=`class Solution {\npublic:\n int solve() {\n  {\n   const char text2[] = "traversal";\n   int frequency2[26] = {};\n   for (char character2 : text2) if (character2 >= 'a') ++frequency2[character2-'a'];\n  }\n  {\n   const char text[] = "traversal";\n   int frequency[26] = {};\n   for (char character : text) if (character >= 'a') ++frequency[character-'a'];\n  }\n  return 0;\n }\n};`;const ranges=findKnownSyntheticRemnantRanges(source);assert.equal(ranges.length,2);let cleaned=source;for(const r of [...ranges].reverse())cleaned=cleaned.slice(0,r.start)+cleaned.slice(r.end);assert.match(cleaned,/return 0/);assert.doesNotMatch(cleaned,/traversal/)});
