(function () {
  const $ = id => document.getElementById(id), form = $('config'), FORM_KEY = 'sidePanelDraftV1'; let status = { state: 'IDLE' }, saveTimer;
  const numeric = ['lastCompleted','endPosition','minutesPerQuestion','minCps','maxCps','minResampleMs','maxResampleMs','minChunkSize','maxChunkSize','pauseProbability','minPauseMs','maxPauseMs','minPointerIntervalMs','maxPointerIntervalMs','nativeMoveDurationMs','pointerAccuracy','maxRetries'];
  const checks = ['skipRestricted','pointerEnabled','editorEnabled','editorConfirmed','pauseWhenHidden','autoRetry','autoSkip','focusMode','keepAwake'];
  function config() { const data = Object.fromEntries(new FormData(form)); for (const name of numeric) data[name] = Number(data[name]); for (const name of checks) data[name] = form.elements[name].checked; return TraversalLab.validateConfig(data); }
  async function call(type, extra = {}) { const result = await chrome.runtime.sendMessage({ type, ...extra }); if (result?.error) throw new Error(result.error); if (result?.state) render(result); return result; }
  function applyConfig(values = {}) { for (const [name, value] of Object.entries(values)) { const field = form.elements[name]; if (!field) continue; if (field.type === 'checkbox') field.checked = Boolean(value); else field.value = String(value); } }
  async function saveDraft() { try { await chrome.storage.local.set({ [FORM_KEY]: config() }); } catch {} }
  function formatTime(ms) { const seconds = Math.max(0, Math.ceil((ms || 0) / 1000)), m = Math.floor(seconds / 60); return `${String(m).padStart(2,'0')}:${String(seconds % 60).padStart(2,'0')}`; }
  function render(next) {
    status = next; $('state').textContent = next.state || 'IDLE'; $('position').textContent = next.current ? `#${next.current.position}` : 'No active problem'; $('queue-source').textContent = next.queueSource === 'user-url-list' ? 'URL queue' : next.queueSource === 'locked-explore-snapshot' ? 'Locked Explore snapshot' : 'No queue'; $('title').textContent = next.current?.problem?.title || (next.state === 'COMPLETED' ? 'Traversal complete' : 'Ready');
    const link = $('problem-link'); if (next.current?.problem?.url) { link.hidden = false; link.href = next.current.problem.url; link.textContent = `${next.current.problem.slug} · ${next.current.problem.url}`; } else link.hidden = true; const fingerprint = $('fingerprint'); fingerprint.hidden = !next.queueFingerprint; fingerprint.textContent = next.queueFingerprint ? `queue ${next.queueFingerprint}` : '';
    $('remaining-time').textContent = formatTime(next.remainingDwellMs); $('completed').textContent = next.counts?.completed || 0; $('skipped').textContent = next.counts?.skipped || 0; $('failed').textContent = next.counts?.failed || 0; $('remaining').textContent = next.remaining || 0; $('cps').textContent = next.currentTargetCps ? Math.round(next.currentTargetCps) : '0'; $('last-action').textContent = next.lastAction || 'Configure a run below.';
    const error = $('error'); error.hidden = !next.recoverableError; error.textContent = next.recoverableError || '';
    const done = (next.counts?.completed || 0) + (next.counts?.skipped || 0), total = next.totalRequested || 0; $('progress-bar').style.width = `${total ? Math.min(100, done / total * 100) : 0}%`;
    const state = next.state, running = ['STARTING','RESOLVING','NAVIGATING','WAITING_FOR_EDITOR','RUNNING','PAUSED','CLEANING','RETRYING'].includes(state); $('start').disabled = running; $('pause').disabled = !['RUNNING','WAITING_FOR_EDITOR','NAVIGATING','RETRYING'].includes(state); $('resume').disabled = state !== 'PAUSED'; $('retry').disabled = !['RUNNING','PAUSED','WAITING_FOR_EDITOR'].includes(state); $('skip').disabled = !['RUNNING','PAUSED','WAITING_FOR_EDITOR'].includes(state); $('remove').disabled = !['RUNNING','PAUSED','WAITING_FOR_EDITOR'].includes(state); $('repair').disabled = !(state === 'PAUSED' && /recovery-journal mismatch/i.test(next.recoverableError || '')); $('stop').disabled = !running;
  }
  async function act(fn) { try { await fn(); } catch (error) { $('error').hidden = false; $('error').textContent = error.message; } }
  $('start').onclick = () => act(async () => { const values = config(); await chrome.storage.local.set({ [FORM_KEY]: values }); await call('START', { config: values }); }); $('pause').onclick = () => act(() => call('PAUSE_RUN')); $('resume').onclick = () => act(() => call('RESUME_RUN')); $('retry').onclick = () => act(() => call('RETRY')); $('skip').onclick = () => act(() => call('SKIP')); $('stop').onclick = () => act(() => call('STOP_RUN'));
  $('remove').onclick = () => act(async () => { const force = /external modification|range changed|missing generated/i.test(status.recoverableError || '') && confirm('The generated range changed. Force cleanup using the recovery anchors? Outside content will be preserved, but you should inspect the editor afterward.'); await call('REMOVE', { force }); });
  $('repair').onclick = () => act(() => call('REPAIR_RECOVERY'));
  async function checkNative() { const node = $('native-status'); node.textContent = 'Checking native companion…'; const result = await call('GET_NATIVE_STATUS'); node.textContent = result.connected ? `Connected: ${result.info.platform} host v${result.info.version}` : result.error; node.classList.toggle('error', !result.connected); }
  $('check-native').onclick = () => act(checkNative);
  $('export').onclick = () => act(async () => { const rows = await call('GET_TELEMETRY'), blob = new Blob([rows.map(row => JSON.stringify(row)).join('\n') + (rows.length ? '\n' : '')], { type: 'application/x-ndjson' }), url = URL.createObjectURL(blob), a = document.createElement('a'); a.href = url; a.download = `gfg-traversal-lab-${new Date().toISOString().replace(/[:.]/g,'-')}.jsonl`; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); });
  chrome.runtime.onMessage.addListener(message => { if (message.type === 'STATUS') render(message.status); });
  chrome.runtime.onMessage.addListener(message => { if (message.type === 'RUNTIME_AID_STATUS') $('runtime-aid').textContent = `Wake lock: ${message.wakeLock}`; });
  function showMode() { const urls = form.elements.traversalMode.value === 'urls'; $('catalog-fields').hidden = urls; $('url-fields').hidden = !urls; const native = form.elements.inputMode.value === 'native'; $('check-native').hidden = !native; if (!native) { $('native-status').textContent = 'Native companion is not required in browser-synthetic mode.'; $('native-status').classList.remove('error'); } }
  form.addEventListener('input', () => { clearTimeout(saveTimer); saveTimer = setTimeout(saveDraft, 250); });
  form.addEventListener('change', event => { showMode(); if (event.target.name === 'inputMode' && event.target.value === 'native') act(checkNative); clearTimeout(saveTimer); saveTimer = setTimeout(saveDraft, 50); });
  (async () => { try { const [draftResult, current] = await Promise.all([chrome.storage.local.get(FORM_KEY), call('GET_STATUS')]); const active = ['STARTING','RESOLVING','NAVIGATING','WAITING_FOR_EDITOR','RUNNING','PAUSED','CLEANING','RETRYING'].includes(current.state); applyConfig(active && current.config ? current.config : draftResult[FORM_KEY]); showMode(); render(current); } catch (error) { $('error').hidden = false; $('error').textContent = error.message; } })();
  setInterval(() => { if (status.dwellDeadline) { status.remainingDwellMs = Math.max(0, status.dwellDeadline - Date.now()); $('remaining-time').textContent = formatTime(status.remainingDwellMs); } }, 500);
})();
